title: Algoritmos y Programación II
description: >
  Página de la materia Algoritmos y Programación II (curso Wachenchauzer).
  Facultad de Ingeniería, Universidad de Buenos Aires.
baseurl: "/algo2"
url: "https://algoritmos-rw.github.io"

theme: minima
markdown: kramdown
kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"
